name: gemini
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - ipywidgets
  - ca-certificates
  - certifi
  - openssl
  - pandas
  - seaborn
  - inflect
  - pip:
    - annotated-types==0.7.0
    - cachetools==5.5.0
    - distro==1.9.0
    - google-ai-generativelanguage==0.6.10
    - google-api-core==2.23.0
    - google-api-python-client==2.154.0
    - google-auth==2.36.0
    - google-auth-httplib2==0.2.0
    - google-generativeai==0.8.3
    - googleapis-common-protos==1.66.0
    - grpcio==1.68.0
    - grpcio-status==1.68.0
    - httplib2==0.22.0
    - jiter==0.9.0
    - kaleido==0.2.1
    - kiwisolver==1.4.8
    - narwhals==1.30.0
    - openai==1.66.3
    - phitter==1.0.0
    - plotly==6.0.0
    - proto-plus==1.25.0
    - protobuf==5.29.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - pydantic==2.10.2
    - pydantic-core==2.27.1
    - pyparsing==3.2.0
    - python-graphviz==0.20.3
    - rsa==4.9
    - tqdm==4.67.1
    - uritemplate==4.1.1
